version: "3.6"
services:
  app:
    build: .
    container_name: dnd-character-sheet-service
  database:
    image: mongo:4.0-xenial
    container_name: character-sheet-db
    volumes:
      - character-sheet-db:/data/db

volumes:
  character-sheet-db: