version: "3.6"
services:
  app:
    volumes:
      - ./src:/app
    ports:
      - "8000:80"
    command: [ "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80" ]
  database:
    ports:
      - "27017:27017"